name: Release

on: 
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: make test

      - name: Build
        run: make TARGETOS=${{matrix.os}} TARGETARCH=${{matrix.arch}} VERSION=${{github.ref_name}} build

      - name: Upload to github release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "./bin/vt-manager-*"
          repo-token: ${{secrets.GITHUB_TOKEN}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ./bin/vt-manager-*

  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin/

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          docker build buildx \
          --push \
          --platform linux/arm64,linux/amd64 \
          --tag nikit0s/vuetorrent-manager:${{github.ref_name}}
          --tag nikit0s/vuetorrent-manager:latest .


