name: Release

on: 
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [darwin, linux]
        arch: [amd64, arm64]
        exclude:
          - os: darwin
            arch: amd64
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: make test

      - name: Build
        run: make TARGETOS=${{matrix.os}} TARGETARCH=${{matrix.arch}} VERSION=${{github.ref_name}} build

      - name: Release 
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "./bin/vt-manager-*"
          repo-token: ${{secrets.GITHUB_TOKEN}}

