name: Release

on: 
  release:
    types:
      - published

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: make test

      - name: Build
        run: |
          make TARGETOS=linux TARGETARCH=amd64 VERSION=${{github.ref_name}} build
          make TARGETOS=linux TARGETARCH=arm64 VERSION=${{github.ref_name}} build

      - name: Upload to github release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "./bin/vt-manager-*"
          repo-token: ${{secrets.GITHUB_TOKEN}}

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build docker image
        run: |
          docker build buildx \
          --push \
          --platform linux/arm64,linux/amd64 \
          --tag nikit0s/vuetorrent-manager:${{github.ref_name}}
          --tag nikit0s/vuetorrent-manager:latest .


